# Generated by Django 3.2.24 on 2025-09-15 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QusetAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiId', models.CharField(max_length=100, verbose_name='项目ID')),
                ('poiName', models.CharField(max_length=200, verbose_name='项目名称')),
                ('source_c', models.CharField(max_length=50, verbose_name='平台来源')),
                ('userName', models.CharField(max_length=100, verbose_name='用户名')),
                ('userAvatar', models.URLField(blank=True, max_length=500, null=True, verbose_name='用户头像')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('likeCount', models.IntegerField(default=0, verbose_name='点赞数')),
                ('replyCount', models.IntegerField(default=0, verbose_name='回复数')),
                ('publishTime', models.DateTimeField(verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论数据',
                'verbose_name_plural': '评论数据',
                'db_table': 'quset_answer',
                'ordering': ['-publishTime'],
            },
        ),
        migrations.CreateModel(
            name='SpiderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiId', models.CharField(max_length=100, unique=True, verbose_name='项目ID')),
                ('poiName', models.CharField(max_length=200, verbose_name='项目名称')),
                ('source_c', models.CharField(max_length=50, verbose_name='平台来源')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='城市')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫基础数据',
                'verbose_name_plural': '爬虫基础数据',
                'db_table': 'spider_base',
            },
        ),
        migrations.CreateModel(
            name='PSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')], max_length=20, verbose_name='情感倾向')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.qusetanswer', verbose_name='评论')),
            ],
            options={
                'verbose_name': '情感分析',
                'verbose_name_plural': '情感分析',
                'db_table': 'p_sentiment',
            },
        ),
    ]
