# Generated by Django 3.2.24 on 2025-09-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    # PSentiment is already defined in initial migration; skip to avoid duplicate table errors in tests.
    operations = []
