# Generated by Django 3.2.24 on 2025-09-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_auto_20250915_2110'),
    ]

    operations = [
    ]
