# Generated by GitHub Copilot to add missing SpiderBase fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spiders", "0004_add_user_management_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderbase',
            name='SalesChannel',
            field=models.CharField(max_length=255, null=True, blank=True, db_column='SalesChannel'),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='request_data',
            field=models.TextField(null=True, db_column='request_data', blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='project_id',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='IteamName',
            field=models.CharField(max_length=255, null=True, blank=True, db_column='IteamName'),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='IteamState',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='poid',
            field=models.BigIntegerField(null=True, blank=True, db_column='poid'),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='sort_type',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='total_collection_page',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='industry',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='spiderbase',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user', db_column='created_by_id'),
        ),
    ]
