# Generated by Django 3.2.24 on 2025-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    # This migration was originally intended to add the 'action' field,
    # but the initial migration already includes the field. To avoid
    # duplicate column errors in test databases we intentionally skip
    # performing any operations here.
    operations = []
