# Generated by Django 3.2.24 on 2025-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='操作类型', default='login'),
            preserve_default=False,
        ),
    ]
