# Generated by Django 3.2.24 on 2025-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250915_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='description',
            field=models.TextField(verbose_name='操作描述', default=''),
            preserve_default=False,
        ),
    ]
