# Generated by Django 3.2.24 on 2025-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250915_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='user_agent',
            field=models.TextField(verbose_name='用户代理', blank=True, null=True, default=''),
            preserve_default=False,
        ),
    ]
