# Generated by Django 3.2.24 on 2025-09-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250915_2019'),
    ]

    # Already present in initial migration; skip to avoid duplicate column errors.
    operations = []
