# Generated by GitHub Copilot to add missing OperationLog fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_operationlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="operation",
            field=models.CharField(default="", max_length=100, verbose_name="操作名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target",
            field=models.CharField(default="", max_length=100, verbose_name="目标对象"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_id",
            field=models.CharField(max_length=50, null=True, verbose_name="目标ID", blank=True),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="details",
            field=models.TextField(null=True, verbose_name="详细信息", blank=True),
        ),
    ]
