# Generated by GitHub Copilot to add missing operation_time field
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_operation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="operation_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="操作时间", auto_now_add=True),
            preserve_default=False,
        ),
    ]
